name: Java CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy: 
      matrix:
        java: [11, 14]

    steps:
    - uses: actions/checkout@v2
    - name: Use JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
